import { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import styles from "../../styles/Components_Style/volunteers/VolunteersMain.module.scss";
import { useEffect, useState } from "react";
import VolunteersCard from "@/Components/volunteersPage/VolunteersCard";
import useContrastClasses from "@/hooks/useContrastClasses";

export interface IProject {
  id: number;
  title: string;
  description: string;
  date_posted: string;
  start_date: string;
  end_date?: string;
  img: string;
}

export interface IVolunteerData {
  id: string;
  fullName?: string;
  age?: number;
  longTerm?: boolean;
  country?: string;
  img: string;
  description?: string;
  projects?: IProject[];
}

interface Props {
  data: IVolunteerData[];
}

const Volunteers: NextPage<Props> = ({ data }) => {
  const { getHeadlineXl, getTextM, getOrangeContrastClasses } = useContrastClasses();
  const headlineXl = getHeadlineXl();
  const textM = getTextM();
  const orangeContrast = getOrangeContrastClasses();
  const [active, setActive] = useState<number>(0);

  const handleItemClick = (index: number) => {
    setActive(index);
  };

  let volunteersArray: IVolunteerData[] = data.filter((item) => {
    if (active === 0) {
      return item.longTerm === true;
    } else {
      return item.longTerm === false;
    }
  });
  console.log(volunteersArray);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div className={styles.volunteersSection}>
        <h1 className={headlineXl}>Нашите Волонери</h1>
        <div className={styles.navigationBar}>
          <div onClick={() => handleItemClick(0)}>
            <h5 className={textM}>Долг Рок</h5>
            <div className={active === 0 ? ` ${orangeContrast} ${styles.bar}` : ""}></div>
          </div>
          <div onClick={() => handleItemClick(1)}>
            <h5 className={textM}>Краток Рок</h5>
            <div className={active === 1 ? `${orangeContrast} ${styles.bar}` : ""}></div>
          </div>
        </div>
        <div className={styles.volunteersContainer}>
          {volunteersArray?.map((item) => (
            <VolunteersCard volunteer={item} />
          ))}
        </div>
      </div>
    </>
  );
};

export default Volunteers;

export const getServerSideProps: GetServerSideProps = async () => {
  const res = await fetch("http://localhost:5001/volunteers");
  const data: IVolunteerData[] = await res.json();

  return {
    props: {
      data,
    },
  };
};
