
import ManagementBoard from '@/Components/team/ManagementBoard';
import TeamSlider from '@/Components/team/TeamSlider';
import { GetServerSideProps, GetStaticPaths, GetStaticProps, NextPage} from 'next';
import Head from 'next/head'
import { ITeamMember } from '.';
import MemberDetails from '@/Components/team/MemberDetails';

interface Props {
  item:ITeamMember
}

const TeamMember: NextPage<Props> = ({item}) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <MemberDetails member={item}/>
    </>
  )
}

export default TeamMember;



export const getStaticPaths: GetStaticPaths = async () => {
  const res = await fetch("http://localhost:5001/members");
  const data:ITeamMember[] = await res.json();

  const paths = data.map((item:ITeamMember)=>{
    return {
      params: {
        id:item.id.toString()
      },
    };
  });
  return {
    paths,
    fallback:false,
  }
};



export const getStaticProps: GetStaticProps = async ({ params }) => {
  if (params?.id) {
    const res = await fetch(`http://localhost:5001/members/${params.id}`);
    const data = await res.json();
    return {  
      props: {
        item: data,
      },
    };
  }
  return {
    props: {
      item: null,
    },
  };
};


