
import ManagementBoard from '@/Components/team/ManagementBoard';
import TeamSlider from '@/Components/team/TeamSlider';
import { GetServerSideProps, GetStaticProps, NextPage} from 'next';
import Head from 'next/head'

export interface ITeamMember {
  id : string;
  fullName: string;
  role: string;
  keyRole:string
  img: string;
  linkedin:string;
  description:string;
}

interface Props {
  teamData:ITeamMember[]
}

const Team: NextPage<Props> = ({teamData}) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <TeamSlider teamData={teamData}/>
      <ManagementBoard teamData={teamData}/>
    </>
  )
}

export default Team;


export const getStaticProps: GetStaticProps = async () => {
  const res = await fetch('http://localhost:5001/members')
  const teamData = await res.json()

  return {
    props: {
      teamData
    },
  };
};
