import HeroSection from "@/Components/homePage/HeroSection";
import LatestNews from "@/Components/homePage/LatestNews";
import Navbar from "@/Components/Navbar";
import Numbers from "@/Components/homePage/Numbers";
import Partners from "@/Components/homePage/Partners";
import Services from "@/Components/homePage/Services";
import UpcomingProject from "@/Components/homePage/UpcomingProject";
import VideoSection from "@/Components/homePage/VideoSection";
import dayjs from "dayjs";
import { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import { useContext } from "react";
import { ThemeContext } from "@/Context/ThemeContext";
import ReadingMask from "@/Components/homePage/ReadingMask";

export interface IProject {
  id: number;
  title: string;
  description: string;
  place: string;
  city: string;
  start_time: string;
  start_date: string;
  end_date: string;
  img: string;
}

export interface INewsData {
  id: number;
  title: string;
  description: string;
  date_posted: string;
  start_date: string;
  end_date?: string;
  img: string;
}

interface Props {
  projectsData: IProject[];
  newsData: INewsData[];
}

const Home: NextPage<Props> = ({ projectsData, newsData }) => {
  const { readingMask } = useContext<any>(ThemeContext);
  //Filter the latestProject
  const findClosestProject = () => {
    let closestProject = null;
    let closestDateDiff = Infinity;
    projectsData.forEach((project: IProject) => {
      const currentDate = dayjs();
      const startDate = dayjs(project.start_date);
      const dateDiff = startDate.diff(currentDate, "days");
      console.log(dateDiff);
      if (!isNaN(dateDiff) && dateDiff >= 0 && dateDiff < closestDateDiff) {
        closestProject = project;
        closestDateDiff = dateDiff;
      }
    });
    return closestProject;
  };
  const closestProject = findClosestProject();
  //News sorting by the date that it is posted
  const sortNewsData = () => {
    const sortedNews = newsData.sort((a, b) => {
      const dateA = dayjs(a.date_posted);
      console.log(dateA);
      const dateB = dayjs(b.date_posted);
      return dateB.diff(dateA);
    });
    return sortedNews.slice(0, 5);
  };
  let sortedNews = sortNewsData();
  console.log(sortedNews);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <HeroSection />
      <UpcomingProject closestProject={closestProject} />
      <Numbers />
      <VideoSection />
      <LatestNews sortedNews={sortedNews} />
      <Services />
      <Partners />
      {readingMask && <ReadingMask />}
    </>
  );
};

export default Home;

export const getServerSideProps: GetServerSideProps = async () => {
  const projectsRes = await fetch("http://localhost:5001/projects");
  const projectsData: IProject[] = await projectsRes.json();

  const newsRes = await fetch("http://localhost:5001/projects");
  const newsData: INewsData[] = await newsRes.json();

  return {
    props: {
      projectsData,
      newsData,
    },
  };
};
