import SingleProjectComponent from "@/Components/projectsPage/SingleProjectComponent";
import { GetStaticPaths, GetStaticProps, NextPage } from "next";
import Head from "next/head";
import React from "react";

export interface IProject {
  id: number;
  title: string;
  description: string;
  date_posted: string;
  start_date: string;
  end_date: string;
  img: string;
}

interface Props {
  item: IProject[];
}

const SingleProject: NextPage<Props> = ({ item }) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <SingleProjectComponent item={item} />
    </>
  );
};

export default SingleProject;

export const getStaticPaths: GetStaticPaths = async () => {
  const res = await fetch("http://localhost:5001/projects");
  const data: IProject[] = await res.json();

  const paths = data.map((item) => {
    return {
      params: {
        id: item.id.toString(),
      },
    };
  });
  return {
    paths,
    fallback: false,
  };
};

export const getStaticProps: GetStaticProps = async ({ params }) => {
  if (params?.id) {
    const res = await fetch(`http://localhost:5001/projects/${params.id}`);
    const data: IProject[] = await res.json();
    return {
      props: {
        item: data,
      },
    };
  }
  return {
    props: {
      item: null,
    },
  };
};
