import SingleProjectComponent from "@/Components/projectsPage/SingleProjectComponent";
import { GetStaticPaths, GetStaticProps, NextPage } from "next";

import { IProducts } from ".";
import Head from "next/head";
import EshopSingleItem from "@/Components/eShop/EshopSingleItem";

interface Props {
  item: IProducts;
}

const SingleItem: NextPage<Props> = ({ item }) => {
  console.log(item?.id);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <EshopSingleItem productItem={item} />
    </>
  );
};

export default SingleItem;

export const getStaticPaths: GetStaticPaths = async () => {
  const res = await fetch("http://localhost:5001/products");
  const data: IProducts[] = await res.json();

  const paths = data.map((item) => {
    return {
      params: {
        id: item.id.toString(),
      },
    };
  });
  return {
    paths,
    fallback: false,
  };
};

export const getStaticProps: GetStaticProps = async ({ params }) => {
  if (params?.id) {
    const res = await fetch(`http://localhost:5001/products/${params.id}`);
    const data: IProducts = await res.json();
    return {
      props: {
        item: data,
      },
    };
  }
  return {
    props: {
      item: null,
    },
  };
};
