import EshopGallery from "@/Components/eShop/EshopGallery";
import EshopSales from "@/Components/eShop/EshopSales";

import { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import { useState } from "react";

export interface IProducts {
  id: string;
  productTitle: string;
  productDescription: string;
  productPrice: string;
  productImg: string;
  productAddInfo: string;
}

interface Props {
  products: IProducts[];
}

const Eshop: NextPage<Props> = ({ products }) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <EshopGallery products={products} />
      <EshopSales products={products} />
    </>
  );
};

export default Eshop;

export const getServerSideProps: GetServerSideProps = async () => {
  const productsRes = await fetch("http://localhost:5001/products");
  const products: IProducts[] = await productsRes.json();

  return {
    props: {
      products,
    },
  };
};
